#!/usr/bin/env bash

cp /go/src/github.com/awslabs/amazon-ecr-credential-helper/bin/local/docker-credential-ecr-login  /home/bin/
cat > creds.json << EOF
{
 	"credHelpers": {
 		"$REGISTRY": "ecr-login"
 	}
}
EOF

if [ ! -f /home/.docker/config.json ]; then
	mkdir -p /home/.docker
	echo "{}" > /home/.docker/config.json
fi

jq -s '.[0] * .[1]' /home/.docker/config.json creds.json > newconfig.json
cp newconfig.json /home/.docker/config.json
